# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-11 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='snippet',
            field=models.TextField(default=''),
        ),
    ]
