# Generated by Django 2.1.7 on 2019-04-02 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0002_breed_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ask.Breed')),
            ],
            options={
                'verbose_name': 'Собака',
                'verbose_name_plural': 'Собаки',
            },
        ),
        migrations.DeleteModel(
            name='StudentInfo',
        ),
    ]
