# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-11 14:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0003_auto_20171211_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='liked',
        ),
    ]
