# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-11 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0006_auto_20171212_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatars/user.png', upload_to='avatars/'),
        ),
    ]
