# Generated by Django 2.1.7 on 2019-04-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0006_auto_20190402_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='testquestion',
            name='next_q1',
            field=models.IntegerField(default='1', unique=True),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='next_q2',
            field=models.IntegerField(default='1', unique=True),
        ),
    ]
