# Generated by Django 2.1.7 on 2019-04-12 08:08

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0008_auto_20190411_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('desc', models.TextField()),
                ('voice', models.IntegerField(choices=[(0, 'silent'), (1, 'normal'), (2, 'loud')], default=0)),
                ('wool', models.IntegerField(choices=[(0, 'none'), (1, 'short'), (2, 'medium'), (3, 'long')], default=0)),
                ('size', models.IntegerField(choices=[(0, 'small'), (1, 'medium'), (2, 'big')], default=0)),
                ('temper', multiselectfield.db.fields.MultiSelectField(choices=[(0, 'calm'), (1, 'kind'), (2, 'loyal'), (3, 'playful')], default=0, max_length=7)),
                ('points', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Порода',
                'verbose_name_plural': 'Породы',
            },
        ),
        migrations.RemoveField(
            model_name='catbreed',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='catbreed',
            name='id',
        ),
        migrations.RemoveField(
            model_name='catbreed',
            name='name',
        ),
        migrations.RemoveField(
            model_name='catbreed',
            name='points',
        ),
        migrations.RemoveField(
            model_name='catbreed',
            name='size',
        ),
        migrations.RemoveField(
            model_name='catbreed',
            name='temper',
        ),
        migrations.RemoveField(
            model_name='catbreed',
            name='voice',
        ),
        migrations.RemoveField(
            model_name='catbreed',
            name='wool',
        ),
        migrations.RemoveField(
            model_name='dogbreed',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='dogbreed',
            name='id',
        ),
        migrations.RemoveField(
            model_name='dogbreed',
            name='name',
        ),
        migrations.RemoveField(
            model_name='dogbreed',
            name='points',
        ),
        migrations.RemoveField(
            model_name='dogbreed',
            name='size',
        ),
        migrations.RemoveField(
            model_name='dogbreed',
            name='temper',
        ),
        migrations.RemoveField(
            model_name='dogbreed',
            name='voice',
        ),
        migrations.RemoveField(
            model_name='dogbreed',
            name='wool',
        ),
        migrations.RemoveField(
            model_name='rodenttype',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='rodenttype',
            name='id',
        ),
        migrations.RemoveField(
            model_name='rodenttype',
            name='name',
        ),
        migrations.RemoveField(
            model_name='rodenttype',
            name='points',
        ),
        migrations.RemoveField(
            model_name='rodenttype',
            name='size',
        ),
        migrations.RemoveField(
            model_name='rodenttype',
            name='temper',
        ),
        migrations.RemoveField(
            model_name='rodenttype',
            name='voice',
        ),
        migrations.RemoveField(
            model_name='rodenttype',
            name='wool',
        ),
        migrations.AddField(
            model_name='catbreed',
            name='breed_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ask.Breed'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dogbreed',
            name='breed_ptr',
            field=models.OneToOneField(auto_created=True, default='0', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ask.Breed'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rodenttype',
            name='breed_ptr',
            field=models.OneToOneField(auto_created=True, default='0', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ask.Breed'),
            preserve_default=False,
        ),
    ]
