# Generated by Django 2.1.7 on 2019-04-12 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0009_auto_20190412_0808'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Животное',
                'verbose_name_plural': 'Животные',
            },
        ),
        migrations.RemoveField(
            model_name='cat',
            name='id',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='id',
        ),
        migrations.RemoveField(
            model_name='rodentia',
            name='id',
        ),
        migrations.AlterField(
            model_name='cat',
            name='breed',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='ask.CatBreed'),
        ),
        migrations.CreateModel(
            name='Carnivora',
            fields=[
                ('animal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ask.Animal')),
            ],
            options={
                'verbose_name': 'Хищное',
                'verbose_name_plural': 'Хищные',
            },
            bases=('ask.animal',),
        ),
        migrations.AddField(
            model_name='rodentia',
            name='animal_ptr',
            field=models.OneToOneField(auto_created=True, default='0', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ask.Animal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cat',
            name='carnivora_ptr',
            field=models.OneToOneField(auto_created=True, default='0', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ask.Carnivora'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dog',
            name='carnivora_ptr',
            field=models.OneToOneField(auto_created=True, default='0', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ask.Carnivora'),
            preserve_default=False,
        ),
    ]
